title: "Les Pierres à Marcel"
description: "Mes pierres de collection"
url: "https://litho.marcelgerber.ch"  # or your custom domain
baseurl: ""  # leave blank if using a custom domain
navigation: main

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: single

collections:
  pages:
    output: true

  pierres:
    output: true
    permalink: /pierres/:path/

exclude:
  - gems/

