title: "Les Pierres à Marcel"
description: "Mes pierres de collection"
url: "https://litho.marcelgerber.ch"
baseurl: ""  # fine if you’re using root domain
navigation: main

remote_theme: "mmistakes/minimal-mistakes"
theme_include_custom_css: true
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: single  # check you have a 'single' layout or switch to a built-in MM layout like 'default' or 'page'

collections:
  pages:
    output: true

  pierres:
    output: true
    permalink: /pierres/:path/

exclude:
  - _pierres.backup
